apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: app:latest
        imagePullPolicy: Never
        name: app
        env:
        - name: CONNECTION_STRING
          # value: root:password@tcp(lms-mysql.default.svc.cluster.local:3306)/defaultdb
          value: root:password@tcp(lms.default.svc.cluster.local:9043)/defaultdb